### ISSUE TITLE
Invalid Public Key

### ISSUE THREAD

**Issue by finleyexp** [dopecoin-dev/dopecoin-paper-wallet#3]
Just used this to create a dopecoin paper wallet. Uploaded the address to Bittrex for a test load and the address came back invalid. 

Please advise.

**Comment by lateminer** [comment]
Sorry for the late reply, should have been fixed now.

**Comment by finleyexp** [comment]
Alright. I'll give it a try and see. Thanks for the response, we're all busy, so I understand delays. :+1:

**Comment by lateminer** [comment]
Can you confirm if it is working fine now?

**Comment by finleyexp** [comment]
Confirmed! Just successfully transfered 1 DopeCoin. Time to shoot some more over. Thank you!

**Comment by dopecoin-dev** [comment]
Issue closed.
